on:
  pull_request:
    paths:
      - updater/**/*
  push:
    paths:
      - updater/**/*

name: Check updater

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure toolchain
        run: |
          rustup toolchain install --profile minimal --no-self-update stable
          rustup default stable
          rustup component add clippy
      - uses: Swatinem/rust-cache@v2

      - run: check --manifest-path updater/Cargo.toml
      - run: clippy --manifest-path updater/Cargo.toml
