name: Release

on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Cargo publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        name: Login
        with:
          command: login
          args: "${{ secrets.CARGO_TOKEN }}"
      - uses: actions-rs/cargo@v1
        name: Publish
        with:
          command: publish
        continue-on-error: true # will error when there's nothing to do
