name: Release

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CARGO_TOKEN:
        required: true
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Cargo publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Configure toolchain
        run: |
          rustup toolchain install --profile minimal --no-self-update stable
          rustup default stable
      - run: cargo login "${{ secrets.CARGO_TOKEN }}"
      - uses: Swatinem/rust-cache@v2
      - run: cargo publish
