name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '38 13 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure toolchain
        run: |
          rustup toolchain install --profile minimal --no-self-update stable
          rustup default stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --manifest-path updater/Cargo.toml

      - name: Clone github/gitignore
        uses: actions/checkout@v4
        with:
          repository: github/gitignore
          path: gitignores
          ref: main

      - name: Run updater
        run: |
          set -euxo pipefail
          updater/target/debug/gitignores-updater \
            --output . \
            --cargo-toml-base updater/gitignores.toml \
            --gitignores-repo gitignores \
            --gh-env-file "$GITHUB_ENV"
          rm -rf gitignores

      - run: cargo check
      - run: cargo fmt
      - run: cargo check

      - run: |
          rustup toolchain install --profile minimal --no-self-update 1.37.0
          rustup default 1.37.0

      - run: cargo check

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        if: env.new_version
        with:
          commit_message: Auto release ${{ env.new_version }}
          tagging_message: "v${{ env.new_version }}"

      - name: Output
        id: output
        run: echo "has_new_version=${{ contains(env.new_version, '.') }}" >> $GITHUB_OUTPUT
    outputs:
      has_new_version: "${{ steps.output.outputs.has_new_version }}"
  release:
    uses: watchexec/gitignores/.github/workflows/release.yml@main
    needs: update
    if: needs.update.outputs.has_new_version == 'true'
    secrets:
      CARGO_TOKEN: "${{ secrets.CARGO_TOKEN }}"
